import type { Article, Video, Ad, Reel, City, CategoryInfo } from './types'

export const CATEGORIES: CategoryInfo[] = [
  { slug: 'lo-ultimo', name: 'Lo último' },
  { slug: 'virales', name: 'Virales' },
  { slug: 'turismo', name: 'Turismo' },
  { slug: 'judicial', name: 'Judicial' },
  { slug: 'especiales', name: 'Especiales' },
  { slug: 'tubarco-cali', name: 'TUBARCO CALI' },
  { slug: 'tubarco-colombia', name: 'TUBARCO COLOMBIA' },
  { slug: 'tubarco-internacional', name: 'TUBARCO INTERNACIONAL' },
  { slug: 'tubarco-valle', name: 'TUBARCO VALLE' },
  { slug: 'tubarco-bogota', name: 'TU BARCO BOGOTÁ' },
  { slug: 'tubarco-narino', name: 'TU BARCO NARIÑO' },
  { slug: 'tubarco-pasto', name: 'TUBARCO PASTO' },
  { slug: 'tubarco-occidente', name: 'TUBARCO OCCIDENTE' },
  { slug: 'cop16', name: 'COP16' },
]

export const CITIES: City[] = [
  { slug: 'cali', name: 'Cali' },
  { slug: 'bogota', name: 'Bogotá' },
  { slug: 'medellin', name: 'Medellín' },
  { slug: 'barranquilla', name: 'Barranquilla' },
  { slug: 'cartagena', name: 'Cartagena' },
  { slug: 'pasto', name: 'Pasto' },
  { slug: 'jamundi', name: 'Jamundí' },
  { slug: 'palmira', name: 'Palmira' },
  { slug: 'buenaventura', name: 'Buenaventura' },
  { slug: 'popayan', name: 'Popayán' },
]

export function categoryName(slug: string): string {
  return CATEGORIES.find((c) => c.slug === slug)?.name ?? slug
}

const STANDARD_CONTENT = `
<p>En un hecho que ha generado amplio debate público, las autoridades locales confirmaron los detalles de una jornada marcada por la tensión y la expectativa ciudadana. Las declaraciones oficiales llegaron luego de varias horas de incertidumbre, mientras medios de comunicación y redes sociales replicaban versiones contradictorias sobre lo ocurrido.</p>
<p>Los voceros institucionales explicaron que el proceso se adelanta con todas las garantías y bajo los protocolos establecidos. Familias, líderes sociales y representantes de la comunidad han solicitado mayor claridad sobre los próximos pasos, especialmente frente a los impactos que esta situación podría tener en la vida cotidiana de los habitantes.</p>
<p>De acuerdo con cifras preliminares reveladas durante la rueda de prensa, las entidades mantienen un seguimiento permanente y han activado los canales de atención correspondientes. "Nuestra prioridad es la tranquilidad de los ciudadanos y la transparencia de la información", señaló uno de los funcionarios a TUBARCO.</p>
<p>Organizaciones sociales y académicos consultados coinciden en que se requieren acciones estructurales para enfrentar este tipo de situaciones. El fenómeno, lejos de ser aislado, responde a dinámicas que se repiten en distintas regiones del país y que exigen respuestas coordinadas entre el gobierno nacional, las administraciones locales y la sociedad civil.</p>
<p>Entre tanto, la comunidad continúa atenta a las actualizaciones oficiales. Las autoridades reiteraron el llamado a denunciar cualquier novedad a través de las líneas habilitadas y a evitar la difusión de información no verificada. TUBARCO continuará haciendo seguimiento a este hecho y ampliará los detalles conforme avance la investigación.</p>
`

export const MOCK_ARTICLES: Article[] = [
  {
    id: '1',
    slug: 'violencia-defensores-ambientales-peru-amazonia',
    title: 'Violencia contra defensores ambientales en Perú expone crisis de protección en la Amazonía',
    excerpt:
      'Líderes indígenas denuncian amenazas sistemáticas mientras la tasa de homicidios de activistas ambientales sigue en aumento en la región.',
    content: STANDARD_CONTENT,
    image: '/images/hero-1.jpg',
    category: 'tubarco-internacional',
    secondaryCategories: ['especiales'],
    author: 'Redacción TUBARCO',
    isAI: false,
    publishedAt: '2026-04-20T14:30:00Z',
    readTime: 6,
    tags: ['Perú', 'Amazonía', 'Derechos humanos', 'Medio ambiente'],
    city: 'Internacional',
    featured: true,
    breaking: true,
    views: 12840,
    likes: 1243,
    dislikes: 87,
  },
  {
    id: '2',
    slug: 'colombia-goleo-argentina-frase-jugador',
    title: 'Colombia los goleó, pero jugador argentino respondió con frase que dio de qué hablar',
    excerpt:
      'Tras la contundente victoria de la selección colombiana, un referente de la albiceleste generó polémica con sus declaraciones en zona mixta.',
    content: STANDARD_CONTENT,
    image: '/images/news-7.jpg',
    category: 'tubarco-internacional',
    author: 'Redacción Deportes',
    isAI: false,
    publishedAt: '2026-04-20T12:15:00Z',
    readTime: 3,
    tags: ['Fútbol', 'Selección Colombia', 'Argentina'],
    city: 'Internacional',
    featured: true,
    views: 9420,
    likes: 892,
    dislikes: 154,
  },
  {
    id: '3',
    slug: 'crimen-grabaciones-bogota-dos-vidas-apagadas',
    title: 'Lo que se sabe del crimen durante grabaciones en Bogotá: dos vidas apagadas en segundos',
    excerpt:
      'Las autoridades entregaron un parte oficial sobre el hecho que conmocionó a la capital en medio de una producción audiovisual.',
    content: STANDARD_CONTENT,
    image: '/images/news-judicial.jpg',
    category: 'judicial',
    secondaryCategories: ['tubarco-bogota'],
    author: 'Andrés Morales',
    isAI: false,
    publishedAt: '2026-04-20T10:00:00Z',
    readTime: 4,
    tags: ['Bogotá', 'Investigación', 'Crimen'],
    city: 'Bogotá',
    featured: true,
    views: 15230,
    likes: 1567,
    dislikes: 203,
  },
  {
    id: '4',
    slug: 'tenencia-ilegal-fauna-jamundi-ocelotes',
    title: 'Tenencia ilegal de fauna en Jamundí terminó con ocelotes rescatados y una mujer capturada',
    excerpt:
      'Un operativo de las autoridades ambientales permitió recuperar dos ejemplares en peligro de extinción que eran mantenidos en cautiverio.',
    content: STANDARD_CONTENT,
    image: '/images/hero-3.jpg',
    category: 'tubarco-cali',
    secondaryCategories: ['judicial'],
    author: 'Redacción TUBARCO CALI',
    isAI: false,
    publishedAt: '2026-04-19T16:20:00Z',
    readTime: 3,
    tags: ['Fauna', 'Jamundí', 'Medio ambiente'],
    city: 'Jamundí',
    views: 6240,
    likes: 412,
    dislikes: 28,
  },
  {
    id: '5',
    slug: 'muerte-ocho-ninos-luisiana-estados-unidos',
    title: 'Una ciudad golpeada: el dolor que deja la muerte de ocho niños en Luisiana, EE. UU.',
    excerpt:
      'La comunidad vive jornadas de luto mientras se investigan las causas del trágico suceso que enlutó a decenas de familias.',
    content: STANDARD_CONTENT,
    image: '/images/hero-2.jpg',
    category: 'tubarco-internacional',
    author: 'Corresponsalía EE. UU.',
    isAI: false,
    publishedAt: '2026-04-19T14:45:00Z',
    readTime: 4,
    tags: ['Estados Unidos', 'Luisiana', 'Tragedia'],
    city: 'Internacional',
    views: 8730,
    likes: 651,
    dislikes: 42,
  },
  {
    id: '6',
    slug: 'jornadas-esterilizacion-gratuita-cali-comunas',
    title: 'Estas son las jornadas de esterilización gratuita en diferentes comunas de Cali esta semana',
    excerpt:
      'La Secretaría de Salud publicó el calendario completo de las brigadas que benefician a miles de familias caleñas.',
    content: STANDARD_CONTENT,
    image: '/images/news-6.jpg',
    category: 'tubarco-cali',
    author: 'Redacción TUBARCO CALI',
    isAI: false,
    publishedAt: '2026-04-20T09:00:00Z',
    readTime: 3,
    tags: ['Cali', 'Salud', 'Mascotas'],
    city: 'Cali',
    views: 4120,
    likes: 328,
    dislikes: 12,
  },
  {
    id: '7',
    slug: 'narcocensura-mexico-periodistas-democracia',
    title: 'Narcocensura en México: violencia contra periodistas y control informativo profundizan crisis democrática',
    excerpt:
      'Un informe especial revela cómo grupos del crimen organizado están silenciando a reporteros y medios en varios estados mexicanos.',
    content: STANDARD_CONTENT,
    image: '/images/hero-4.jpg',
    category: 'especiales',
    secondaryCategories: ['tubarco-internacional'],
    author: 'Investigación TUBARCO',
    isAI: false,
    publishedAt: '2026-04-17T11:30:00Z',
    readTime: 9,
    tags: ['México', 'Periodismo', 'Libertad de prensa'],
    city: 'Internacional',
    featured: true,
    views: 18940,
    likes: 2145,
    dislikes: 118,
  },
  {
    id: '8',
    slug: 'ofensiva-farallones-cali-mineria-ilegal',
    title: 'Anuncian ofensiva en Farallones de Cali con nuevo plan para contrarrestar la minería ilegal',
    excerpt:
      'Autoridades ambientales, Ejército y Policía articulan estrategia para proteger uno de los parques naturales más emblemáticos.',
    content: STANDARD_CONTENT,
    image: '/images/news-5.jpg',
    category: 'tubarco-cali',
    author: 'Redacción TUBARCO',
    isAI: false,
    publishedAt: '2026-04-17T08:45:00Z',
    readTime: 4,
    tags: ['Farallones', 'Cali', 'Medio ambiente'],
    city: 'Cali',
    views: 5680,
    likes: 510,
    dislikes: 34,
  },
  {
    id: '9',
    slug: 'pacifico-escondido-valle-del-cauca-playas-virgenes',
    title: 'El Pacífico escondido del Valle del Cauca: playas vírgenes, selva y cultura que aún escapan del turismo masivo',
    excerpt:
      'Un recorrido por los rincones menos conocidos de la costa vallecaucana revela una riqueza natural y cultural impresionante.',
    content: STANDARD_CONTENT,
    image: '/images/news-tourism.jpg',
    category: 'turismo',
    secondaryCategories: ['tubarco-valle'],
    author: 'Laura Pérez',
    isAI: false,
    publishedAt: '2026-04-18T15:10:00Z',
    readTime: 7,
    tags: ['Valle del Cauca', 'Turismo', 'Pacífico'],
    city: 'Buenaventura',
    views: 7310,
    likes: 823,
    dislikes: 24,
  },
  {
    id: '10',
    slug: 'suizo-colombiana-casarse-vida-cambio',
    title: '"Mi vida cambió por completo": lo que significa para un suizo casarse con una colombiana',
    excerpt:
      'Un testimonio que se hizo viral en redes sociales muestra los contrastes culturales que enfrentan parejas binacionales.',
    content: STANDARD_CONTENT,
    image: '/images/news-viral.jpg',
    category: 'virales',
    author: 'Redacción Virales',
    isAI: false,
    publishedAt: '2026-03-19T17:00:00Z',
    readTime: 3,
    tags: ['Viral', 'Suiza', 'Colombia'],
    city: 'Internacional',
    views: 24180,
    likes: 3412,
    dislikes: 145,
  },
  {
    id: '11',
    slug: 'charco-cristalino-valle-del-cauca-naturaleza',
    title: 'Charco cristalino y rodeado de naturaleza: un paraíso cerca de emblemática hacienda en el Valle del Cauca',
    excerpt:
      'Un destino poco explorado entre montañas ofrece a los viajeros una experiencia única de desconexión y aventura.',
    content: STANDARD_CONTENT,
    image: '/images/news-tourism.jpg',
    category: 'turismo',
    secondaryCategories: ['tubarco-valle'],
    author: 'Redacción Turismo',
    isAI: false,
    publishedAt: '2026-04-15T12:00:00Z',
    readTime: 4,
    tags: ['Valle del Cauca', 'Naturaleza', 'Turismo'],
    city: 'Palmira',
    views: 3940,
    likes: 289,
    dislikes: 18,
  },
  {
    id: '12',
    slug: 'estrategia-plateado-jamundi-control-seguridad',
    title: 'Estrategia de El Plateado, opción que plantean para recuperar el control en Jamundí',
    excerpt:
      'Expertos en seguridad analizan la viabilidad de replicar el modelo aplicado en Argelia, Cauca, en el municipio vallecaucano.',
    content: STANDARD_CONTENT,
    image: '/images/news-judicial.jpg',
    category: 'tubarco-cali',
    secondaryCategories: ['judicial'],
    author: 'Análisis TUBARCO',
    isAI: false,
    publishedAt: '2026-04-20T13:40:00Z',
    readTime: 5,
    tags: ['Seguridad', 'Jamundí', 'Valle del Cauca'],
    city: 'Jamundí',
    views: 4820,
    likes: 342,
    dislikes: 29,
  },
  {
    id: '13',
    slug: 'petro-ecuador-embajadora-regreso',
    title: 'Petro endurece postura con Ecuador y ordena el regreso inmediato de su embajadora',
    excerpt:
      'La decisión se produce en medio del escalamiento diplomático por el incremento de aranceles a productos colombianos.',
    content: STANDARD_CONTENT,
    image: '/images/news-8.jpg',
    category: 'tubarco-colombia',
    secondaryCategories: ['tubarco-internacional'],
    author: 'Redacción Política',
    isAI: false,
    publishedAt: '2026-04-10T16:50:00Z',
    readTime: 4,
    tags: ['Petro', 'Ecuador', 'Diplomacia'],
    city: 'Bogotá',
    featured: true,
    views: 11240,
    likes: 1120,
    dislikes: 284,
  },
  {
    id: '14',
    slug: 'liliana-villarreal-artemis-colombiana-nasa',
    title: 'Liliana Villarreal, la colombiana que lideró el regreso de Artemis II: "A los 7 años supe que quería ser astronauta"',
    excerpt:
      'La ingeniera vallecaucana habla sobre el reto de coordinar una de las misiones espaciales más importantes de la NASA.',
    content: STANDARD_CONTENT,
    image: '/images/hero-4.jpg',
    category: 'tubarco-colombia',
    author: 'María Camila Rojas',
    isAI: false,
    publishedAt: '2026-04-11T10:20:00Z',
    readTime: 6,
    tags: ['NASA', 'Artemis', 'Colombia'],
    city: 'Internacional',
    views: 15680,
    likes: 2012,
    dislikes: 42,
  },
  {
    id: '15',
    slug: 'inflacion-global-marzo-2026-bancos-centrales',
    title: 'La inflación global repunta en marzo de 2026 mientras bancos centrales evalúan nuevos recortes de tasas',
    excerpt:
      'Los datos publicados por organismos internacionales muestran un escenario económico mixto con retos para América Latina.',
    content: STANDARD_CONTENT,
    image: '/images/news-8.jpg',
    category: 'tubarco-internacional',
    author: 'Redacción Economía',
    isAI: true,
    publishedAt: '2026-03-19T09:00:00Z',
    readTime: 4,
    tags: ['Economía', 'Inflación', 'Tasas'],
    city: 'Internacional',
    views: 6710,
    likes: 431,
    dislikes: 56,
  },
  {
    id: '16',
    slug: 'cancelar-servicio-telecomunicaciones-nueva-norma',
    title: 'Cancelar el servicio sin trabas: nueva norma cambia las reglas para usuarios de telecomunicaciones',
    excerpt:
      'La Comisión de Regulación emitió una resolución que facilita el cierre de contratos y amplía derechos de los consumidores.',
    content: STANDARD_CONTENT,
    image: '/images/news-6.jpg',
    category: 'tubarco-colombia',
    author: 'Redacción TUBARCO',
    isAI: false,
    publishedAt: '2026-03-27T11:00:00Z',
    readTime: 3,
    tags: ['Telecomunicaciones', 'Consumidores'],
    city: 'Bogotá',
    views: 5320,
    likes: 612,
    dislikes: 38,
  },
  {
    id: '17',
    slug: 'alerta-cali-mensajes-falsos-multas-estafa',
    title: 'Alerta en Cali por mensajes falsos de multas: así están intentando engañar a conductores',
    excerpt:
      'Secretaría de Movilidad advierte sobre una nueva modalidad de estafa digital que suplanta a la entidad.',
    content: STANDARD_CONTENT,
    image: '/images/hero-3.jpg',
    category: 'tubarco-cali',
    author: 'Redacción TUBARCO CALI',
    isAI: false,
    publishedAt: '2026-03-26T14:00:00Z',
    readTime: 3,
    tags: ['Cali', 'Estafa', 'Movilidad'],
    city: 'Cali',
    views: 7890,
    likes: 489,
    dislikes: 22,
  },
  {
    id: '18',
    slug: 'onu-reparacion-esclavitud-decision-historica',
    title: 'La ONU pone en debate mundial la reparación por la esclavitud tras decisión histórica',
    excerpt:
      'Por primera vez, el organismo reconoce formalmente la necesidad de avanzar hacia mecanismos de justicia reparativa.',
    content: STANDARD_CONTENT,
    image: '/images/especial-derechos.jpg',
    category: 'tubarco-internacional',
    secondaryCategories: ['especiales'],
    author: 'Corresponsalía ONU',
    isAI: false,
    publishedAt: '2026-03-26T13:00:00Z',
    readTime: 5,
    tags: ['ONU', 'Derechos humanos'],
    city: 'Internacional',
    views: 9240,
    likes: 874,
    dislikes: 62,
  },
  {
    id: '19',
    slug: 'mono-bebe-punch-peluche-final-feliz',
    title: 'La historia del mono bebé Punch que fue rechazado por su madre y se aferró a un peluche terminó en un final feliz',
    excerpt:
      'La conmovedora historia del primate, que recorrió el mundo gracias a las redes sociales, tuvo un desenlace inesperado.',
    content: STANDARD_CONTENT,
    image: '/images/news-viral.jpg',
    category: 'virales',
    author: 'Redacción Virales',
    isAI: false,
    publishedAt: '2026-02-21T09:30:00Z',
    readTime: 3,
    tags: ['Viral', 'Animales'],
    city: 'Internacional',
    views: 32120,
    likes: 4821,
    dislikes: 98,
  },
  {
    id: '20',
    slug: 'autoridades-intensifican-controles-cali-pescado',
    title: 'Autoridades intensifican controles en Cali por alta demanda de pescado en Semana Santa',
    excerpt:
      'Secretaría de Salud y autoridades sanitarias refuerzan operativos en plazas de mercado para garantizar la calidad de los productos.',
    content: STANDARD_CONTENT,
    image: '/images/news-8.jpg',
    category: 'tubarco-cali',
    author: 'Redacción TUBARCO CALI',
    isAI: false,
    publishedAt: '2026-03-27T08:00:00Z',
    readTime: 3,
    tags: ['Cali', 'Semana Santa', 'Salud'],
    city: 'Cali',
    views: 4230,
    likes: 312,
    dislikes: 14,
  },
  {
    id: '21',
    slug: 'cali-hora-planeta-edificios-publicos',
    title: 'Cali se une a la Hora del Planeta: edificios públicos apagarán sus luces y hogares podrán sumarse',
    excerpt:
      'La administración municipal invitó a la ciudadanía a participar en la jornada global de conciencia ambiental.',
    content: STANDARD_CONTENT,
    image: '/images/news-5.jpg',
    category: 'tubarco-cali',
    author: 'Redacción TUBARCO CALI',
    isAI: false,
    publishedAt: '2026-03-27T15:30:00Z',
    readTime: 2,
    tags: ['Cali', 'Medio ambiente', 'Hora del Planeta'],
    city: 'Cali',
    views: 2840,
    likes: 245,
    dislikes: 8,
  },
  {
    id: '22',
    slug: 'crimen-organizado-mar-ecuatoriano-pescadores',
    title: 'Crimen organizado en el mar ecuatoriano: pescadores enfrentan violencia, extorsión y desapariciones',
    excerpt:
      'Un especial de TUBARCO revela la dramática situación que viven las comunidades pesqueras del Pacífico ecuatoriano.',
    content: STANDARD_CONTENT,
    image: '/images/especial-derechos.jpg',
    category: 'especiales',
    secondaryCategories: ['tubarco-internacional'],
    author: 'Investigación TUBARCO',
    isAI: false,
    publishedAt: '2026-03-27T07:00:00Z',
    readTime: 10,
    tags: ['Ecuador', 'Pesca', 'Crimen organizado'],
    city: 'Internacional',
    featured: true,
    views: 13420,
    likes: 1542,
    dislikes: 89,
  },
  {
    id: '23',
    slug: 'parque-turistico-playa-verde-pradera-valle',
    title: 'Parque turístico Playa Verde: piscina, cascada y río entre las montañas de Pradera, Valle del Cauca',
    excerpt:
      'A solo una hora de Cali, este destino combina naturaleza, aventura y tradición familiar en un entorno impresionante.',
    content: STANDARD_CONTENT,
    image: '/images/news-tourism.jpg',
    category: 'turismo',
    secondaryCategories: ['tubarco-valle'],
    author: 'Redacción Turismo',
    isAI: false,
    publishedAt: '2024-11-10T10:00:00Z',
    readTime: 5,
    tags: ['Valle del Cauca', 'Pradera', 'Turismo'],
    city: 'Palmira',
    views: 18450,
    likes: 1823,
    dislikes: 42,
  },
  {
    id: '24',
    slug: 'bus-mio-bala-investigacion-cali',
    title: 'Bus del MIO impactado por una bala, investigan si fue un ataque o bala perdida',
    excerpt:
      'El hecho ocurrió en el oriente de la ciudad y las autoridades adelantan las investigaciones para esclarecer lo sucedido.',
    content: STANDARD_CONTENT,
    image: '/images/news-judicial.jpg',
    category: 'judicial',
    secondaryCategories: ['tubarco-cali'],
    author: 'Andrés Morales',
    isAI: false,
    publishedAt: '2026-03-15T19:20:00Z',
    readTime: 3,
    tags: ['Cali', 'MIO', 'Investigación'],
    city: 'Cali',
    views: 9240,
    likes: 412,
    dislikes: 168,
  },
]

export const MOCK_VIDEOS: Video[] = [
  {
    id: 'v1',
    title: '¿La democracia no está garantizada como derecho en América Latina?',
    youtubeId: '1MG0L9qFmCQ',
    thumbnail: '/images/video-thumb-1.jpg',
    duration: '8:42',
    views: '48.2K',
    publishedAt: '2026-04-18T10:00:00Z',
  },
  {
    id: 'v2',
    title: 'Le disparan 7 veces en su casa estando embarazada… alcalde estaría implicado',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: '/images/video-thumb-2.jpg',
    duration: '12:15',
    views: '92.1K',
    publishedAt: '2026-04-17T14:30:00Z',
  },
  {
    id: 'v3',
    title: 'El Pacífico colombiano: selva, cultura y playas vírgenes del Valle del Cauca',
    youtubeId: 'dQw4w9WgXcQ',
    thumbnail: '/images/video-thumb-3.jpg',
    duration: '6:28',
    views: '31.5K',
    publishedAt: '2026-04-16T09:15:00Z',
  },
  {
    id: 'v4',
    title: 'Especial: Derechos negados en América Latina — la investigación completa',
    thumbnail: '/images/especial-derechos.jpg',
    duration: '18:45',
    views: '22.8K',
    publishedAt: '2026-04-12T11:00:00Z',
    youtubeId: 'dQw4w9WgXcQ',
  },
]

export const MOCK_REELS: Reel[] = [
  {
    id: 'r1',
    title: 'Así viven los pescadores del Pacífico colombiano',
    thumbnail: '/images/reel-1.jpg',
    duration: '0:58',
  },
  {
    id: 'r2',
    title: 'Momento viral: el suizo que habla como caleño',
    thumbnail: '/images/reel-2.jpg',
    duration: '0:45',
  },
  {
    id: 'r3',
    title: 'Cascadas escondidas en el Valle del Cauca',
    thumbnail: '/images/reel-3.jpg',
    duration: '1:02',
  },
  {
    id: 'r4',
    title: 'La Feria de Cali como nunca la has visto',
    thumbnail: '/images/reel-4.jpg',
    duration: '0:52',
  },
]

export const MOCK_ADS: Ad[] = [
  {
    id: 'ad1',
    title: 'Sé parte del #PeriodismoCiudadano',
    sponsor: 'TUBARCO',
    description:
      'En TUBARCO creemos en una comunicación plural. Cuéntanos tu historia y llega a miles de lectores en Colombia y América Latina.',
    cta: 'Quiero participar',
    url: '#',
    image: '/images/hero-1.jpg',
  },
  {
    id: 'ad2',
    title: 'Turismo en el Valle del Cauca',
    sponsor: 'TURISMO VALLE',
    description:
      'Descubre los destinos más increíbles cerca de Cali: cascadas, reservas naturales y pueblos con encanto. Planea tu próxima escapada.',
    cta: 'Explorar destinos',
    url: '#',
    image: '/images/news-tourism.jpg',
  },
  {
    id: 'ad3',
    title: 'Newsletter TUBARCO',
    sponsor: 'TUBARCO',
    description:
      'Recibe cada mañana las noticias más importantes de Colombia y el mundo directamente en tu correo. 100% gratis.',
    cta: 'Suscribirme',
    url: '#',
    image: '/images/especial-derechos.jpg',
  },
]
